USE [master]
GO

/****** Object:  Database [TradeReportDP]    Script Date: 16.07.2025 22:26:35 ******/
CREATE DATABASE [TradeReportDP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TradeReportDP', FILENAME = N'D:\server\MSSQL15.DP_SERVER\MSSQL\DATA\TradeReportDP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TradeReportDP_log', FILENAME = N'D:\server\MSSQL15.DP_SERVER\MSSQL\DATA\TradeReportDP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TradeReportDP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TradeReportDP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TradeReportDP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TradeReportDP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TradeReportDP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TradeReportDP] SET ARITHABORT OFF 
GO

ALTER DATABASE [TradeReportDP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TradeReportDP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TradeReportDP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TradeReportDP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TradeReportDP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TradeReportDP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TradeReportDP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TradeReportDP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TradeReportDP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TradeReportDP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TradeReportDP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TradeReportDP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TradeReportDP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TradeReportDP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TradeReportDP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TradeReportDP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TradeReportDP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TradeReportDP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TradeReportDP] SET  MULTI_USER 
GO

ALTER DATABASE [TradeReportDP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TradeReportDP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TradeReportDP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TradeReportDP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TradeReportDP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TradeReportDP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TradeReportDP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TradeReportDP] SET  READ_WRITE 
GO

