USE [master]
GO

/****** Object:  Database [TradeReportDP]    Script Date: 26.02.2024 15:17:19 ******/
CREATE DATABASE [TradeReportDP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TradeReportDP', FILENAME = N'D:\server\MSSQL15.DP_SERVER\MSSQL\DATA\TradeReportDP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TradeReportDP_log', FILENAME = N'D:\server\MSSQL15.DP_SERVER\MSSQL\DATA\TradeReportDP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TradeReportDP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TradeReportDP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TradeReportDP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TradeReportDP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TradeReportDP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TradeReportDP] SET ARITHABORT OFF 
GO

ALTER DATABASE [TradeReportDP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TradeReportDP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TradeReportDP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TradeReportDP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TradeReportDP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TradeReportDP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TradeReportDP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TradeReportDP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TradeReportDP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TradeReportDP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TradeReportDP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TradeReportDP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TradeReportDP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TradeReportDP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TradeReportDP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TradeReportDP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TradeReportDP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TradeReportDP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TradeReportDP] SET  MULTI_USER 
GO

ALTER DATABASE [TradeReportDP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TradeReportDP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TradeReportDP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TradeReportDP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TradeReportDP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TradeReportDP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TradeReportDP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TradeReportDP] SET  READ_WRITE 
GO

USE [TradeReportDP]
GO

/****** Object:  Table [dbo].[Product]    Script Date: 26.02.2024 15:18:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[PricePurchase] [int] NULL,
	[PriceSale] [int] NULL,
	[Type] [nchar](50) NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [TradeReportDP]
GO

/****** Object:  Table [dbo].[Providers]    Script Date: 26.02.2024 15:18:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Providers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](60) NOT NULL,
	[Adress] [nvarchar](100) NULL,
	[Tel] [nvarchar](15) NULL,
	[Email] [nvarchar](50) NULL,
 CONSTRAINT [PK_Providers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [TradeReportDP]
GO

/****** Object:  Table [dbo].[Shipment]    Script Date: 26.02.2024 15:18:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Shipment](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Product] [int] NULL,
	[Ammount] [int] NOT NULL,
	[TradeDate] [datetime] NULL,
	[SaleDate] [datetime] NULL,
	[Note] [nvarchar](100) NULL,
	[Provider] [int] NULL,
 CONSTRAINT [PK_Shipment] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Shipment] ADD  CONSTRAINT [DF_Shipment_Ammount]  DEFAULT ((1)) FOR [Ammount]
GO

ALTER TABLE [dbo].[Shipment]  WITH CHECK ADD  CONSTRAINT [FK_Shipment_Product] FOREIGN KEY([Product])
REFERENCES [dbo].[Product] ([Id])
GO

ALTER TABLE [dbo].[Shipment] CHECK CONSTRAINT [FK_Shipment_Product]
GO

ALTER TABLE [dbo].[Shipment]  WITH CHECK ADD  CONSTRAINT [FK_Shipment_Providers] FOREIGN KEY([Provider])
REFERENCES [dbo].[Providers] ([Id])
GO

ALTER TABLE [dbo].[Shipment] CHECK CONSTRAINT [FK_Shipment_Providers]
GO

